[browser]
gatherUsageStats = false

[server]
headless = true
address = "127.0.0.1"
port = 8501

[client]
toolbarMode = "minimal"
showErrorDetails = true

[ui]
hideTopBar = true

[theme]
base = "dark"
primaryColor = "#7B61FF"
backgroundColor = "#0b1020"
secondaryBackgroundColor = "#121a2b"
textColor = "#f1f5fc"
font = "sans serif"
